// Auto-generated search term patch for ARASAAC candidate search.
// Use these terms for candidate search; do not display unverified images automatically.
export const improvedCardSearchTerms: Record<string, string[]> = {
  "istekler-yardim": ["help", "ayuda", "need help", "emergency"],
  "istekler-mola": ["break", "rest", "descanso", "pausa"],
  "istekler-saril": ["hug", "abrazar", "abrazo"],
  "istekler-bir-daha": ["again", "more", "otra vez", "de nuevo", "mas"],
  "istekler-bitti": ["finished", "all done", "terminado", "fin"],
  "istekler-bekle": ["wait", "esperar", "stop"],
  "istekler-ac": ["open", "abrir"],
  "istekler-kapat": ["close", "cerrar"],
  "istekler-istiyorum": ["want", "I want", "quiero", "pedir"],
  "istekler-istemiyorum": ["don't want", "no quiero", "no", "reject"],
  "yiyecek-elma": ["apple", "manzana"],
  "yiyecek-muz": ["banana", "platano", "plátano"],
  "yiyecek-ekmek": ["bread", "pan"],
  "yiyecek-corba": ["soup", "sopa"],
  "yiyecek-pilav": ["rice", "arroz"],
  "yiyecek-peynir": ["cheese", "queso"],
  "yiyecek-yogurt": ["yogurt", "yogur"],
  "yiyecek-tavuk": ["chicken", "pollo"],
  "yiyecek-kofte": ["meatball", "albóndiga", "albondiga"],
  "yiyecek-makarna": ["pasta", "macaroni", "macarrones"],
  "yiyecek-patates": ["potato", "patata", "papa"],
  "yiyecek-domates": ["tomato", "tomate"],
  "yiyecek-salatalik": ["cucumber", "pepino"],
  "yiyecek-portakal": ["orange", "naranja"],
  "yiyecek-cilek": ["strawberry", "fresa"],
  "yiyecek-biskuvi": ["cookie", "biscuit", "galleta"],
  "icecek-su": ["water", "agua"],
  "icecek-sut": ["milk", "leche"],
  "icecek-meyve-suyu": ["juice", "zumo", "jugo"],
  "icecek-ayran": ["yogurt drink", "drink", "bebida", "yogur"],
  "icecek-cay": ["tea", "té", "infusion"],
  "icecek-ic": ["drink", "beber", "tomar"],
  "icecek-kakao": ["cocoa", "cacao", "hot chocolate", "chocolate"],
  "icecek-limonata": ["lemonade", "limonada"],
  "icecek-sicak-cikolata": ["hot chocolate", "chocolate caliente", "cacao"],
  "icecek-gazoz": ["soda", "soft drink", "gaseosa", "refresco"],
  "duygular-mutlu": ["happy", "feliz", "contento"],
  "duygular-uzgun": ["sad", "triste"],
  "duygular-kizgin": ["angry", "enfadado", "enojado"],
  "duygular-korktum": ["afraid", "scared", "miedo", "asustado"],
  "duygular-sakin": ["calm", "quiet", "tranquilo"],
  "duygular-heyecanli": ["excited", "emocionado", "ilusionado"],
  "duygular-saskin": ["surprised", "sorprendido"],
  "duygular-sikildim": ["bored", "aburrido"],
  "duygular-utandim": ["embarrassed", "shy", "vergüenza", "avergonzado"],
  "duygular-merakli": ["curious", "curioso"],
  "beden-saglik-bas": ["head", "cabeza", "headache", "dolor de cabeza"],
  "beden-saglik-karin": ["belly", "stomach", "barriga", "dolor de barriga"],
  "beden-saglik-dis": ["tooth", "teeth", "diente", "dolor de muelas"],
  "beden-saglik-el": ["hand", "mano"],
  "beden-saglik-yorgun": ["tired", "cansado"],
  "beden-saglik-aciktim": ["hungry", "hunger", "hambre"],
  "beden-saglik-susadim": ["thirsty", "sed", "drink water"],
  "beden-saglik-ayagim": ["foot", "pie"],
  "beden-saglik-bogazim": ["throat", "garganta", "sore throat", "dolor de garganta"],
  "beden-saglik-gozum": ["eye", "ojo"],
  "beden-saglik-kulagim": ["ear", "oreja"],
  "beden-saglik-usuyorum": ["cold", "frio", "frío"],
  "tuvalet-hijyen-tuvalet": ["toilet", "bathroom", "wc", "aseo", "baño", "retrete"],
  "tuvalet-hijyen-cis": ["pee", "urinate", "orinar", "pis"],
  "tuvalet-hijyen-kaka": ["poop", "feces", "caca", "hacer caca"],
  "tuvalet-hijyen-el-yika": ["wash hands", "lavar manos", "lavarse las manos"],
  "tuvalet-hijyen-dis-fircala": ["brush teeth", "cepillar dientes", "lavarse los dientes"],
  "tuvalet-hijyen-banyo": ["shower", "ducha", "bath", "baño"],
  "tuvalet-hijyen-sac-tara": ["comb hair", "peinar", "peine"],
  "tuvalet-hijyen-sabun": ["soap", "jabon", "jabón"],
  "tuvalet-hijyen-havlu": ["towel", "toalla"],
  "tuvalet-hijyen-tuvalet-kagidi": ["toilet paper", "papel higienico", "papel higiénico"],
  "eylemler-otur": ["sit", "sit down", "sentar", "sentarse"],
  "eylemler-kalk": ["stand up", "get up", "levantarse"],
  "eylemler-kos": ["run", "correr"],
  "eylemler-yuru": ["walk", "caminar", "andar"],
  "eylemler-oku": ["read", "leer"],
  "eylemler-uyu": ["sleep", "dormir"],
  "eylemler-yaz": ["write", "escribir"],
  "eylemler-oyna": ["play", "jugar"],
  "eylemler-dinle": ["listen", "hear", "escuchar", "oir"],
  "eylemler-bak": ["look", "see", "mirar", "ver"],
  "kisiler-anne": ["mother", "mom", "madre", "mama"],
  "kisiler-baba": ["father", "dad", "padre", "papa"],
  "kisiler-abla": ["sister", "hermana", "big sister"],
  "kisiler-abi": ["brother", "hermano", "big brother"],
  "kisiler-arkadas": ["friend", "amigo", "amiga"],
  "kisiler-ogretmen": ["teacher", "maestro", "profesor"],
  "kisiler-teyze": ["aunt", "tia", "tía"],
  "kisiler-amca": ["uncle", "tio", "tío"],
  "kisiler-buyukanne": ["grandmother", "grandma", "abuela"],
  "kisiler-buyukbaba": ["grandfather", "grandpa", "abuelo"],
  "yerler-ev": ["home", "house", "casa"],
  "yerler-okul": ["school", "escuela", "colegio"],
  "yerler-park": ["park", "parque"],
  "yerler-market": ["supermarket", "market", "mercado", "supermercado"],
  "yerler-araba": ["car", "coche", "auto"],
  "yerler-bahce": ["garden", "jardin", "jardín"],
  "yerler-oyun-alani": ["playground", "play area", "parque infantil", "patio"],
  "yerler-kutuphane": ["library", "biblioteca"],
  "yerler-yol": ["road", "path", "camino", "carretera"],
  "yerler-restoran": ["restaurant", "restaurante"],
  "ev-yatak": ["bed", "cama"],
  "ev-masa": ["table", "mesa"],
  "ev-koltuk": ["sofa", "armchair", "sillon", "sillón"],
  "ev-mutfak": ["kitchen", "cocina"],
  "ev-kapi": ["door", "puerta"],
  "ev-isik": ["lamp", "light", "luz", "lampara", "lámpara"],
  "ev-hali": ["carpet", "rug", "alfombra"],
  "ev-pencere": ["window", "ventana"],
  "ev-televizyon": ["television", "tv", "televisor"],
  "ev-dolap": ["wardrobe", "closet", "cupboard", "armario"],
  "okul-defter": ["notebook", "cuaderno"],
  "okul-kalem": ["pencil", "pen", "lapiz", "lápiz"],
  "okul-sinif": ["classroom", "class", "aula", "clase"],
  "okul-teneffus": ["recess", "break", "recreo"],
  "okul-boya": ["paint", "coloring", "pintura"],
  "okul-canta": ["school bag", "backpack", "mochila"],
  "okul-silgi": ["eraser", "rubber", "goma", "borrador"],
  "okul-kitap": ["book", "libro"],
  "okul-makas": ["scissors", "tijeras"],
  "okul-cetvel": ["ruler", "regla"],
  "oyun-oyuncak-top": ["ball", "pelota"],
  "oyun-oyuncak-bebek": ["doll", "baby doll", "muñeca", "bebe"],
  "oyun-oyuncak-araba": ["toy car", "coche de juguete"],
  "oyun-oyuncak-yapboz": ["puzzle", "jigsaw puzzle", "puzle", "rompecabezas"],
  "oyun-oyuncak-lego": ["blocks", "building blocks", "bloques", "lego"],
  "oyun-oyuncak-salincak": ["swing", "columpio"],
  "oyun-oyuncak-bloklar": ["blocks", "building blocks", "bloques"],
  "oyun-oyuncak-tren": ["toy train", "train", "tren de juguete"],
  "oyun-oyuncak-kukla": ["puppet", "marioneta", "titere"],
  "oyun-oyuncak-balon": ["balloon", "globo", "balon"],
  "rutinler-uyan": ["wake up", "despertar", "despertarse"],
  "rutinler-giyin": ["get dressed", "dress", "vestirse"],
  "rutinler-kahvalti": ["breakfast", "desayuno"],
  "rutinler-okula-git": ["go to school", "ir al colegio", "ir a la escuela"],
  "rutinler-eve-don": ["go home", "return home", "volver a casa"],
  "rutinler-ders": ["lesson", "class", "leccion", "clase"],
  "rutinler-oyun-zamani": ["play time", "time to play", "jugar"],
  "rutinler-aksam": ["evening routine", "evening", "noche"],
  "rutinler-dinlen": ["rest", "relax", "descansar"],
  "rutinler-yat": ["go to bed", "bedtime", "acostarse"],
  "sosyal-ifadeler-merhaba": ["hello", "hi", "hola"],
  "sosyal-ifadeler-gule-gule": ["goodbye", "bye", "adios", "adiós"],
  "sosyal-ifadeler-lutfen": ["please", "por favor"],
  "sosyal-ifadeler-tesekkurler": ["thank you", "thanks", "gracias"],
  "sosyal-ifadeler-ozur-dilerim": ["sorry", "lo siento", "perdon"],
  "sosyal-ifadeler-evet": ["yes", "si", "sí"],
  "sosyal-ifadeler-hayir": ["no"],
  "sosyal-ifadeler-tamam": ["okay", "ok", "vale", "de acuerdo"],
  "sosyal-ifadeler-bilmiyorum": ["I don't know", "no sé", "no lo se"],
  "sosyal-ifadeler-nasilsin": ["how are you", "como estas", "cómo estás"],
  "sosyal-ifadeler-gunaydin": ["good morning", "buenos dias", "buenos días"],
  "sosyal-ifadeler-iyi-geceler": ["good night", "buenas noches"],
  "duyusal-ihtiyaclar-sessiz": ["quiet", "silence", "silencio", "callar"],
  "duyusal-ihtiyaclar-kulaklik": ["headphones", "auriculares", "cascos"],
  "duyusal-ihtiyaclar-sik-sik": ["tight hug", "deep pressure", "abrazo fuerte"],
  "duyusal-ihtiyaclar-zipla": ["jump", "saltar"],
  "duyusal-ihtiyaclar-sallan": ["swing", "rocking", "balancear", "columpiar"],
  "duyusal-ihtiyaclar-karanlik": ["dark", "oscuro"],
  "duyusal-ihtiyaclar-yuksek-ses": ["loud noise", "noise", "ruido", "sonido fuerte"],
  "duyusal-ihtiyaclar-parlak-isik": ["bright light", "light", "luz brillante"],
  "duyusal-ihtiyaclar-kalabalik": ["crowd", "crowded", "multitud", "aglomeracion"],
  "duyusal-ihtiyaclar-sarilmak-istemiyorum": ["no hug", "don't hug", "no abrazar", "no quiero abrazo"],
  "guvenlik-dur": ["stop", "parar", "alto"],
  "guvenlik-yavas": ["slow", "slowly", "despacio", "lento"],
  "guvenlik-elimi-tut": ["hold my hand", "hand", "coger la mano", "dar la mano"],
  "guvenlik-bekle": ["stay back", "back", "wait", "esperar", "atras"],
  "guvenlik-tehlike": ["danger", "warning", "peligro"],
  "guvenlik-kemer": ["seat belt", "belt", "cinturon", "cinturón de seguridad"],
  "guvenlik-acil-yardim": ["emergency help", "help", "ayuda", "emergencia"],
  "guvenlik-sicak": ["hot", "caliente"],
  "guvenlik-soguk": ["cold", "frio", "frío"],
  "guvenlik-kayboldum": ["lost", "perdido", "desorientado"],
  "zaman-simdi": ["now", "ahora"],
  "zaman-sonra": ["later", "after", "despues", "después"],
  "zaman-sabah": ["morning", "mañana"],
  "zaman-ogle": ["noon", "midday", "mediodia", "mediodía"],
  "zaman-aksam": ["evening", "night", "tarde", "noche"],
  "zaman-gece": ["night", "noche"],
  "zaman-hemen": ["right now", "immediately", "ahora mismo"],
  "zaman-bugun": ["today", "hoy"],
  "zaman-dun": ["yesterday", "ayer"],
  "zaman-yarin": ["tomorrow", "mañana"],
  "gunler-pazartesi": ["monday", "lunes"],
  "gunler-sali": ["tuesday", "martes"],
  "gunler-carsamba": ["wednesday", "miercoles", "miércoles"],
  "gunler-persembe": ["thursday", "jueves"],
  "gunler-cuma": ["friday", "viernes"],
  "gunler-cumartesi": ["saturday", "sabado", "sábado"],
  "gunler-pazar": ["sunday", "domingo"],
  "sayilar-sifir": ["zero", "0", "cero"],
  "sayilar-bir": ["one", "1", "uno"],
  "sayilar-iki": ["two", "2", "dos"],
  "sayilar-uc": ["three", "3", "tres"],
  "sayilar-dort": ["four", "4", "cuatro"],
  "sayilar-bes": ["five", "5", "cinco"],
  "sayilar-alti": ["six", "6", "seis"],
  "sayilar-yedi": ["seven", "7", "siete"],
  "sayilar-sekiz": ["eight", "8", "ocho"],
  "sayilar-dokuz": ["nine", "9", "nueve"],
  "sayilar-on": ["ten", "10", "diez"],
  "renkler-kirmizi": ["red", "rojo"],
  "renkler-mavi": ["blue", "azul"],
  "renkler-sari": ["yellow", "amarillo"],
  "renkler-yesil": ["green", "verde"],
  "renkler-turuncu": ["orange color", "naranja", "anaranjado"],
  "renkler-mor": ["purple", "violet", "morado", "violeta"],
  "renkler-pembe": ["pink", "rosa"],
  "renkler-siyah": ["black", "negro"],
  "renkler-beyaz": ["white", "blanco"],
  "renkler-kahverengi": ["brown", "marron", "marrón"],
  "kiyafetler-tisort": ["t-shirt", "shirt", "camiseta"],
  "kiyafetler-pantolon": ["pants", "trousers", "pantalon", "pantalón"],
  "kiyafetler-corap": ["socks", "calcetines"],
  "kiyafetler-ayakkabi": ["shoes", "zapatos"],
  "kiyafetler-mont": ["coat", "jacket", "abrigo", "chaqueta"],
  "kiyafetler-sapka": ["hat", "cap", "gorra", "sombrero"],
  "kiyafetler-kazak": ["sweater", "jumper", "jersey"],
  "kiyafetler-elbise": ["dress", "vestido"],
  "kiyafetler-etek": ["skirt", "falda"],
  "kiyafetler-pijama": ["pajamas", "pyjamas", "pijama"],
  "hava-durumu-gunesli": ["sunny", "sun", "sol", "soleado"],
  "hava-durumu-bulutlu": ["cloudy", "cloud", "nublado", "nube"],
  "hava-durumu-yagmurlu": ["rainy", "rain", "lluvia", "lluvioso"],
  "hava-durumu-karli": ["snowy", "snow", "nieve", "nevado"],
  "hava-durumu-ruzgarli": ["windy", "wind", "viento"],
  "hava-durumu-firtina": ["storm", "thunderstorm", "tormenta"],
  "hava-durumu-sisli": ["foggy", "fog", "niebla"],
  "hava-durumu-gok-gurultusu": ["thunder", "thunderstorm", "trueno"],
  "hava-durumu-gokkusagi": ["rainbow", "arco iris", "arcoiris"],
  "hava-durumu-serin": ["cool weather", "fresh", "fresco"],
  "tasitlar-araba": ["car", "coche", "auto"],
  "tasitlar-otobus": ["bus", "autobus", "autobús"],
  "tasitlar-tren": ["train", "tren"],
  "tasitlar-ucak": ["airplane", "plane", "avion", "avión"],
  "tasitlar-bisiklet": ["bicycle", "bike", "bicicleta"],
  "tasitlar-gemi": ["ship", "boat", "barco"],
  "tasitlar-motosiklet": ["motorcycle", "moto"],
  "tasitlar-taksi": ["taxi"],
  "tasitlar-ambulans": ["ambulance", "ambulancia"],
  "tasitlar-traktor": ["tractor"],
  "spor-ilgi-futbol": ["football", "soccer", "fútbol", "futbol"],
  "spor-ilgi-top": ["ball", "football ball", "pelota"],
  "spor-ilgi-mac": ["match", "game", "football match", "partido"],
  "spor-ilgi-gol": ["goal", "gol"],
  "spor-ilgi-forma": ["jersey", "uniform", "camiseta"],
  "spor-ilgi-aslan": ["lion", "leon", "león"],
  "spor-ilgi-galatasaray": ["lion", "football", "red yellow", "leon", "fútbol"],
  "hayvanlar-kedi": ["cat", "gato"],
  "hayvanlar-kopek": ["dog", "perro"],
  "hayvanlar-kus": ["bird", "pajaro", "pájaro", "ave"],
  "hayvanlar-balik": ["fish", "pez"],
  "hayvanlar-tavsan": ["rabbit", "conejo"],
  "hayvanlar-at": ["horse", "caballo"],
  "hayvanlar-inek": ["cow", "vaca"],
  "hayvanlar-koyun": ["sheep", "oveja"],
  "hayvanlar-kaplumbaga": ["turtle", "tortoise", "tortuga"],
  "hayvanlar-kelebek": ["butterfly", "mariposa"],
  "mutfak-tabak": ["plate", "dish", "plato"],
  "mutfak-kasik": ["spoon", "cuchara"],
  "mutfak-catal": ["fork", "tenedor"],
  "mutfak-bicak": ["knife", "cuchillo"],
  "mutfak-bardak": ["glass", "cup", "vaso"],
  "mutfak-tencere": ["pot", "saucepan", "olla", "cacerola"],
  "mutfak-tava": ["pan", "frying pan", "sarten", "sartén"],
  "mutfak-buzdolabi": ["fridge", "refrigerator", "nevera", "frigorifico"],
  "mutfak-firin": ["oven", "horno"],
  "mutfak-ocak": ["stove", "cooker", "hornilla", "cocina"],
  "banyo-kuvet": ["bathtub", "bath", "bañera"],
  "banyo-dus-basligi": ["shower head", "ducha"],
  "banyo-lavabo": ["sink", "washbasin", "lavabo"],
  "banyo-ayna": ["mirror", "espejo"],
  "banyo-dis-macunu": ["toothpaste", "pasta de dientes"],
  "banyo-sampuan": ["shampoo", "champu", "champú"],
  "banyo-sabunluk": ["soap dish", "soap", "jabonera", "jabon"],
  "banyo-tarak": ["comb", "peine"],
  "banyo-kirli-sepeti": ["laundry basket", "basket", "cesto de ropa", "cesta"],
  "banyo-musluk": ["tap", "faucet", "grifo"],
  "uyku-uyku-zamani": ["sleep time", "bedtime", "dormir"],
  "uyku-yastik": ["pillow", "almohada"],
  "uyku-battaniye": ["blanket", "manta"],
  "uyku-gece-lambasi": ["night light", "lamp", "luz nocturna", "lampara"],
  "uyku-ninni": ["lullaby", "song", "cancion de cuna"],
  "uyku-ruya": ["dream", "sueño"],
  "uyku-uykum-var": ["sleepy", "tired", "tengo sueño"],
  "uyku-gozlerim-kapali": ["closed eyes", "eyes closed", "ojos cerrados"],
  "uyku-sessiz-oda": ["quiet room", "silence", "habitacion silenciosa"],
  "uyku-dinlen": ["rest", "relax", "descansar"],
  "disari-yuruyus": ["walk", "walking", "paseo", "caminar"],
  "disari-kaydirak": ["slide", "tobogan", "tobogán"],
  "disari-kum-havuzu": ["sandbox", "sandpit", "arenero"],
  "disari-cimen": ["grass", "cesped", "césped"],
  "disari-cicek": ["flower", "flor"],
  "disari-agac": ["tree", "arbol", "árbol"],
  "disari-bank": ["bench", "banco"],
  "disari-piknik": ["picnic"],
  "disari-deniz": ["sea", "ocean", "mar"],
  "disari-golge": ["shade", "shadow", "sombra"],
  "teknoloji-tablet": ["tablet"],
  "teknoloji-telefon": ["phone", "telephone", "telefono", "teléfono"],
  "teknoloji-bilgisayar": ["computer", "ordenador", "computadora"],
  "teknoloji-ekran": ["screen", "monitor", "pantalla"],
  "teknoloji-klavye": ["keyboard", "teclado"],
  "teknoloji-fare": ["computer mouse", "mouse", "raton", "ratón"],
  "teknoloji-sarj-cihazi": ["charger", "charging cable", "cargador"],
  "teknoloji-hoparlor": ["speaker", "altavoz"],
  "teknoloji-uzaktan-kumanda": ["remote control", "mando", "control remoto"],
  "teknoloji-kamera": ["camera", "camara", "cámara"],
}
